export default {
  id: "bazaarlink",
  priority: 45,
  hasFree: true,
  alias: "bzl",
  display: {
    name: "Bazaarlink",
    icon: "storefront",
    color: "#EC4899",
    textIcon: "BZ",
    website: "https://bazaarlink.ai",
    notice: { apiKeyUrl: "https://bazaarlink.ai" },
  },
  category: "freeTier",
  transport: {
    baseUrl: "https://bazaarlink.ai/api/v1/chat/completions",
    validateUrl: "https://bazaarlink.ai/api/v1/models",
    thinkingFormat: "openai",
  },
  models: [
    { id: "auto:free", name: "Auto Free (Zero Cost)" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "gpt-5.5", name: "GPT-5.5" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "grok-4.3", name: "Grok 4.3" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "minimax-m3", name: "MiniMax M3", contextLength: 1048576, supportsVision: true },
    { id: "llama-3.3-70b-instruct", name: "Llama 3.3 70B" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
  ],
  modelsFetcher: { url: "https://bazaarlink.ai/api/v1/models", type: "openai" },
  passthroughModels: true,
};
