const DEFAULT_BASE_URL = "https://api.cliproxyapi.com/v1";

export default {
  id: "cliproxyapi",
  priority: 28,
  alias: "cliproxyapi",
  aliases: ["cliproxy", "cli-proxy-api", "cli-proxy"],
  uiAlias: "cliproxy",
  display: {
    name: "CLIProxyAPI",
    icon: "hub",
    color: "#0F766E",
    textIcon: "CP",
    website: "https://cliproxyapi.com",
    notice: {
      text: "OpenAI-compatible proxy endpoint. Override the base URL per connection when using a self-hosted or private CLIProxyAPI server.",
      apiKeyUrl: "https://cliproxyapi.com",
    },
  },
  category: "apikey",
  hasProviderSpecificData: true,
  thinkingConfig: {
    options: ["auto", "none", "low", "medium", "high"],
    defaultMode: "auto",
  },
  transport: {
    baseUrl: `${DEFAULT_BASE_URL}/chat/completions`,
    responsesUrl: `${DEFAULT_BASE_URL}/responses`,
    validateUrl: `${DEFAULT_BASE_URL}/models`,
    thinkingFormat: "openai",
    quirks: {
      configurableBaseUrl: true,
      disablePromptCacheByDefault: true,
    },
  },
  transports: [
    { format: "openai", baseUrl: `${DEFAULT_BASE_URL}/chat/completions`, quirks: { configurableBaseUrl: true } },
    { format: "openai-responses", baseUrl: `${DEFAULT_BASE_URL}/responses`, quirks: { configurableBaseUrl: true } },
  ],
  models: [
    { id: "gpt-5.5", name: "GPT 5.5", supportsReasoning: true, toolCalling: true },
    { id: "gpt-5.4", name: "GPT 5.4", supportsReasoning: true, toolCalling: true },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini", supportsReasoning: true, toolCalling: true },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex", supportsReasoning: true, toolCalling: true },
    { id: "gpt-4.1", name: "GPT 4.1", toolCalling: true },
    { id: "gpt-4.1-mini", name: "GPT 4.1 Mini", toolCalling: true },
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large", kind: "embedding" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small", kind: "embedding" },
    { id: "tts-1/alloy", name: "TTS 1 / Alloy", kind: "tts" },
    { id: "tts-1-hd/alloy", name: "TTS 1 HD / Alloy", kind: "tts" },
    { id: "gpt-4o-mini-tts/alloy", name: "GPT 4o Mini TTS / Alloy", kind: "tts" },
    { id: "whisper-1", name: "Whisper 1", params: ["language", "response_format", "temperature", "prompt"], kind: "stt" },
    { id: "gpt-4o-transcribe", name: "GPT 4o Transcribe", params: ["language", "response_format", "temperature", "prompt"], kind: "stt" },
    { id: "gpt-4o-mini-transcribe", name: "GPT 4o Mini Transcribe", params: ["language", "response_format", "temperature", "prompt"], kind: "stt" },
    { id: "gpt-image-2", name: "GPT Image 2", capabilities: ["text2img", "edit"], params: ["n", "size", "quality", "background", "output_format", "response_format"], kind: "image" },
    { id: "gpt-image-1", name: "GPT Image 1", capabilities: ["text2img", "edit"], params: ["n", "size", "quality", "background", "output_format", "response_format"], kind: "image" },
  ],
  serviceKinds: ["llm", "embedding", "tts", "stt", "image", "imageToText", "webSearch"],
  ttsConfig: {
    baseUrl: `${DEFAULT_BASE_URL}/audio/speech`,
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
    defaultModel: "gpt-4o-mini-tts",
  },
  sttConfig: {
    baseUrl: `${DEFAULT_BASE_URL}/audio/transcriptions`,
    authType: "apikey",
    authHeader: "bearer",
    format: "openai",
  },
  embeddingConfig: { baseUrl: `${DEFAULT_BASE_URL}/embeddings`, authType: "apikey", authHeader: "bearer" },
  imageConfig: {
    baseUrl: `${DEFAULT_BASE_URL}/images/generations`,
    editsUrl: `${DEFAULT_BASE_URL}/images/edits`,
    variationsUrl: `${DEFAULT_BASE_URL}/images/variations`,
    authType: "apikey",
    authHeader: "bearer",
  },
  searchViaChat: { defaultModel: "gpt-4.1-mini", pricingUrl: "https://cliproxyapi.com" },
  modelsFetcher: { url: `${DEFAULT_BASE_URL}/models`, type: "openai" },
  passthroughModels: true,
};
