export default {
  id: "cloudflare-ai",
  priority: 60,
  hasFree: true,
  alias: "cloudflare-ai",
  aliases: [
    "cf",
  ],
  uiAlias: "cf",
  display: {
    name: "Cloudflare",
    icon: "cloud",
    color: "#F38020",
    textIcon: "CF",
    website: "https://developers.cloudflare.com/workers-ai/",
    notice: {
      text: "Workers AI free tier. Requires a Cloudflare API token and Account ID.",
      apiKeyUrl: "https://dash.cloudflare.com/profile/api-tokens",
    },
  },
  category: "freeTier",
  hasProviderSpecificData: true,
  transport: {
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1/chat/completions",
    thinkingFormat: "openai",
  },
  models: [
    { id: "@cf/meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct" },
    { id: "@cf/meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct" },
    { id: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", name: "Llama 3.1 8B Instruct FP8 Fast" },
    { id: "@cf/meta/llama-3.1-8b-instruct-fp8", name: "Llama 3.1 8B Instruct FP8" },
    { id: "@cf/meta/llama-3.1-8b-instruct-awq", name: "Llama 3.1 8B Instruct AWQ" },
    { id: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", name: "Llama 3.1 70B Instruct FP8 Fast" },
    { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct FP8 Fast" },
    { id: "@cf/meta/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17B 16E Instruct" },
    { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B" },
    { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B Instruct" },
    { id: "@cf/moonshotai/kimi-k2.5", name: "Kimi K2.5" },
    { id: "@cf/moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "@cf/moonshotai/kimi-k2.7-code", name: "Kimi K2.7 Code" },
    { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "@cf/zai-org/glm-5.2", name: "GLM 5.2" },
    { id: "@cf/qwen/qwq-32b", name: "QwQ 32B" },
    { id: "@cf/qwen/qwen2.5-coder-32b-instruct", name: "Qwen 2.5 Coder 32B Instruct" },
    { id: "@cf/qwen/qwen3-30b-a3b-fp8", name: "Qwen3 30B A3B FP8" },
    { id: "@cf/openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "@cf/openai/gpt-oss-20b", name: "GPT OSS 20B" },
    { id: "@cf/google/gemma-4-26b-a4b-it", name: "Gemma 4 26B A4B IT" },
    { id: "@cf/nvidia/nemotron-3-120b-a12b", name: "Nemotron 3 120B A12B" },
    { id: "@cf/ibm-granite/granite-4.0-h-micro", name: "Granite 4.0 H Micro" },
    { id: "@cf/aisingapore/gemma-sea-lion-v4-27b-it", name: "Gemma SEA-LION v4 27B IT" },
    { id: "@cf/black-forest-labs/flux-2-klein-9b", name: "FLUX.2 Klein 9B", params: ["size"], kind: "image" },
    { id: "@cf/black-forest-labs/flux-2-klein-4b", name: "FLUX.2 Klein 4B", params: ["size"], kind: "image" },
    { id: "@cf/black-forest-labs/flux-2-dev", name: "FLUX.2 Dev", params: ["size"], kind: "image" },
    { id: "@cf/leonardo/lucid-origin", name: "Lucid Origin", params: ["size"], kind: "image" },
    { id: "@cf/leonardo/phoenix-1.0", name: "Phoenix 1.0", params: ["size"], kind: "image" },
    { id: "@cf/black-forest-labs/flux-1-schnell", name: "FLUX.1 Schnell", params: ["size"], kind: "image" },
    { id: "@cf/bytedance/stable-diffusion-xl-lightning", name: "SDXL Lightning", params: ["size"], kind: "image" },
    { id: "@cf/lykon/dreamshaper-8-lcm", name: "DreamShaper 8 LCM", params: ["size"], kind: "image" },
    { id: "@cf/runwayml/stable-diffusion-v1-5-img2img", name: "Stable Diffusion v1.5 Img2Img", params: ["size"], capabilities: ["edit"], kind: "image" },
    { id: "@cf/runwayml/stable-diffusion-v1-5-inpainting", name: "Stable Diffusion v1.5 Inpainting", params: ["size"], capabilities: ["edit","mask"], kind: "image" },
    { id: "@cf/stabilityai/stable-diffusion-xl-base-1.0", name: "SDXL Base 1.0", params: ["size"], kind: "image" },
  ],
  serviceKinds: ["llm","image"],
  imageConfig: { baseUrl: "https://api.cloudflare.com/client/v4/accounts" },
};
